// One-off/regeneratable script: builds src/data/presetComps/index.js, a static
// barrel file that explicitly imports every bundled comp JSON. Re-run this
// whenever files are added/removed under src/data/presetComps/.
// Usage: node scripts/generatePresetCompsIndex.js
//
// El servidor de desarrollo VIGILA este fichero, asi que ejecutarlo con `npm
// start` levantado recompila y recarga la pagina sola: no hace falta reiniciar
// nada para que una comp recien soltada en la carpeta entre en la app. De ahi
// que se pueda importar ademas de ejecutar -- `watchPresetComps.js` lo llama en
// bucle-- y de ahi que solo escriba cuando el contenido cambia de verdad: si
// reescribiera el fichero identico en cada aviso del sistema de ficheros,
// webpack se pasaria la vida recompilando.
const fs = require('fs');
const path = require('path');

const presetCompsDir = path.join(__dirname, '..', 'src', 'data', 'presetComps');
const outFile = path.join(presetCompsDir, 'index.js');

const varName = (fileName, idx) => `comp${idx}`;

const buildContent = (files) => {
  const importLines = files.map((f, idx) => `import ${varName(f, idx)} from './${f}';`).join('\n');
  const entryLines = files
    .map((f, idx) => `  { key: ${JSON.stringify(f.replace(/\.json$/, ''))}, data: ${varName(f, idx)} }`)
    .join(',\n');

  return `// AUTO-GENERATED by scripts/generatePresetCompsIndex.js — do not edit by hand.
// Re-run that script after adding/removing files in this folder.
${importLines}

export const PRESET_COMP_ENTRIES = [
${entryLines}
];
`;
};

/**
 * Regenera el barril.
 *
 * @returns {{files: string[], changed: boolean}} `changed` es false cuando el
 *   fichero ya decia exactamente esto, que es el caso normal cuando lo dispara
 *   un vigilante de ficheros.
 */
const generatePresetCompsIndex = () => {
  const files = fs
    .readdirSync(presetCompsDir)
    .filter((f) => f.endsWith('.json'))
    .sort((a, b) => a.localeCompare(b));

  const content = buildContent(files);
  const previous = fs.existsSync(outFile) ? fs.readFileSync(outFile, 'utf8') : null;
  if (previous === content) return { files, changed: false };

  fs.writeFileSync(outFile, content, 'utf8');
  return { files, changed: true };
};

module.exports = { generatePresetCompsIndex, presetCompsDir, outFile };

if (require.main === module) {
  const { files, changed } = generatePresetCompsIndex();
  console.log(
    changed
      ? `Wrote ${files.length} entries to ${outFile}`
      : `Already up to date: ${files.length} entries in ${outFile}`
  );
}
