// One-off/regeneratable script: builds src/data/presetComps/index.js, a static
// barrel file that explicitly imports every bundled comp JSON. Re-run this
// whenever files are added/removed under src/data/presetComps/.
// Usage: node scripts/generatePresetCompsIndex.js
const fs = require('fs');
const path = require('path');

const presetCompsDir = path.join(__dirname, '..', 'src', 'data', 'presetComps');
const outFile = path.join(presetCompsDir, 'index.js');

const files = fs
  .readdirSync(presetCompsDir)
  .filter((f) => f.endsWith('.json'))
  .sort((a, b) => a.localeCompare(b));

const varName = (fileName, idx) => `comp${idx}`;

const importLines = files.map((f, idx) => `import ${varName(f, idx)} from './${f}';`).join('\n');
const entryLines = files
  .map((f, idx) => `  { key: ${JSON.stringify(f.replace(/\.json$/, ''))}, data: ${varName(f, idx)} }`)
  .join(',\n');

const content = `// AUTO-GENERATED by scripts/generatePresetCompsIndex.js — do not edit by hand.
// Re-run that script after adding/removing files in this folder.
${importLines}

export const PRESET_COMP_ENTRIES = [
${entryLines}
];
`;

fs.writeFileSync(outFile, content, 'utf8');
console.log(`Wrote ${files.length} entries to ${outFile}`);
